version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "@playwright/test"
    groups:
      production-dependencies:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      development-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "pip"
    directory: "/sample"
    schedule:
      interval: "weekly"
    groups:
      python-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directories:
      - "/"
      - "/sample"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker-compose"
    directories:
      - "/.devcontainer"
      - "/sample"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "mcr.microsoft.com/playwright"
