x-dev: &dev
  image: ghcr.io/her0e1c1/tango
  build:
    context: .
  stdin_open: true
  tty: true
  environment:
    VITE_DB_HOST: db
    VITE_DB_PORT: ${VITE_DB_PORT:-8080}
  working_dir: /workspace
  volumes:
    - .:/workspace
    - node_modules:/workspace/node_modules
  entrypoint: bash

services:
  db:
    image: gcr.io/google.com/cloudsdktool/google-cloud-cli:emulators
    platform: linux/amd64
    entrypoint: gcloud
    command: emulators firestore start --host-port "0.0.0.0:${VITE_DB_PORT:-8080}" --rules=/firestore.rules
    volumes:
      - ./firestore.rules:/firestore.rules
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:${VITE_DB_PORT:-8080}"]
      start_period: 5s
      interval: 60s
      retries: 3

  dev:
    <<: *dev
    profiles:
      - dev

volumes:
  node_modules:
