
services:
  db:
    image: google/cloud-sdk
    platform: linux/amd64
    entrypoint: gcloud
    command: emulators firestore start --host-port "0.0.0.0:$VITE_DB_PORT" --rules=/firestore.rules
    volumes:
      - ./firestore.rules:/firestore.rules
    healthcheck:
      test: ["CMD", "curl", "localhost:$VITE_DB_PORT"]
      start_period: 5s
      interval: 60s
      retries: 3

  base: &base
    image: ghcr.io/her0e1c1/tango
    build: .
    stdin_open: true
    tty: true
    environment:
      - VITE_DB_HOST=db
      - VITE_DB_PORT=$VITE_DB_PORT
    working_dir: /workspace
    volumes:
      - .:/workspace
      - /workspace/node_modules  # empty
    profiles:
      - base
    entrypoint: bash

  test:
    <<: *base
    depends_on:
      db:
        condition: service_healthy
    entrypoint: vitest
