version: 2
jobs:
  build-job:
    docker:
      - image: circleci/node:12
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: cp ./src/secret.ts.example ./src/secret.ts
      - run: yarn test:all
  deploy-job:
    docker:
      - image: circleci/node:12
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: printf "cat <<EOS\n`cat ./src/secret.ts.example`\nEOS\n" | sh > ./src/secret.ts
      # - run: NODE_ENV=production yarn build
      - run: yarn add expo-cli 
      - run: yarn run expo-cli login -u "$EXPO_USERNAME" -p "$EXPO_PASSWORD" 2>&1 > /dev/null
      - run: yarn run expo-cli whoami
      - run:
         command: yarn run expo-cli publish --non-interactive
         no_output_timeout: 30m
      # - run: yarn web-build
      # - run: yarn firebase deploy --token "$FIREBASE_TOKEN" --only hosting

workflows:
   version: 2
   build-deploy:
     jobs:
       - build-job
       - deploy-job:
           requires:
             - build-job
           filters:
             branches:
               only: master
