version: 2
jobs:
  build-job:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn build || true
  deploy-job:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: printf "cat <<EOS\n`cat ./src/secret.ts.example`\nEOS\n" | sh > ./src/secret.ts
      - run: yarn build || true
      - run: node ./node_modules/exp/bin/exp.js login -u "$EXPO_USERNAME" -p "$EXPO_PASSWORD"
      - run: node ./node_modules/exp/bin/exp.js whoami
      - run: node ./node_modules/exp/bin/exp.js publish --non-interactive

workflows:
   version: 2
   build-deploy:
     jobs:
       - build-job
       - deploy-job:
           requires:
             - build-job
           filters:
             branches:
               only: master
