name: Question
description: Ask a question about the project.
title: "[Question]: "
labels: ["question"]
body:
  - type: textarea
    id: question
    attributes:
      label: Question
      description: Describe specifically what you would like to know.
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Context
      description: Describe the context and anything you have already tried.
    validations:
      required: true
