
x-tty: &tty
  stdin_open: true
  tty: true

x-image: &image
  image: ghcr.io/her0e1c1/tango-sample:${BRANCH:-latest}
  build: .

x-base: &base
  <<: *image
  working_dir: /workspace
  volumes:
    - ./build:/workspace/build
    - ./test:/workspace/test
    - ./generate.py:/workspace/generate.py

services:
  image: *image

  bash:
    <<: [*base, *tty]
    entrypoint: bash

  test:
    <<: [*base, *tty]
    entrypoint: py.test

  gen:
    <<: [*base, *tty]
    entrypoint: python generate.py ./test -o build/output.json

  lock:
    image: python:3.13
    working_dir: /buildspace
    volumes:
      - ./Pipfile:/buildspace/Pipfile
      - ./:/workspace
    command:
      - bash
      - -c
      - |
        pip install --upgrade pip
        pip install pipenv
        pipenv lock
        cp /buildspace/Pipfile.lock /workspace
