name: Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yml

  deploy:
    needs: [test]
    name: Deploy To Firebase
    permissions:
      contents: read
      id-token: write
    environment: production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: jdx/mise-action@c2a87611a18de5b3828c5652fe268e992400cb5c # v4.3.0

      - run: echo VITE_PROJECT_ID="${{ secrets.VITE_PROJECT_ID }}" >> .env
      - run: echo VITE_WEB_API_KEY="${{ secrets.VITE_WEB_API_KEY }}" >> .env
      - run: echo VITE_REPOSITORY_URL="https://github.com/her0e1c1/tango" >> .env

      - run: mise run init

      - run: mise run build

      - uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3
        with:
          project_id: tango-ts
          workload_identity_provider: ${{ vars.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.GCP_DEPLOY_SERVICE_ACCOUNT }}

      - run: npx firebase deploy --project tango-ts --only hosting,firestore:rules
