name: Update Docker Image

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches:
      - "**"

jobs:
  lint:
    name: Lint Dockerfiles
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: hadolint/hadolint-action@2a66e89f53d0771bb131a7fa31f3136336094aa6 # v3.4.0
        with:
          dockerfile: Dockerfile
          recursive: true
          failure-threshold: warning

  changes:
    name: Check Docker Image Changes
    if: ${{ github.event_name != 'workflow_dispatch' && github.event_name != 'pull_request' }}
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.changed.outputs.any_modified }}
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Check changed files
        id: changed
        uses: tj-actions/changed-files@9426d40962ed5378910ee2e21d5f8c6fcbf2dd96 # v47.0.6
        with:
          files: |
            .dockerignore
            Dockerfile
            package.json
            package-lock.json

  push:
    name: Update Docker Image
    needs: [changes, lint]
    if: ${{ !cancelled() && needs.lint.result == 'success' && github.event_name != 'pull_request' && (github.event_name == 'workflow_dispatch' || needs.changes.outputs.image == 'true') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Log into registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.actor }}/tango:latest
