name: E2E

on:
  workflow_call:
  workflow_dispatch:

env:
  COMPOSE_PROJECT_NAME: tango-e2e

permissions:
  contents: read

jobs:
  e2e:
    name: E2E
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Log into registry
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0

      - name: Build test image
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          context: .
          load: true
          tags: ghcr.io/her0e1c1/tango:latest
          cache-from: type=gha,scope=tango-e2e
          cache-to: type=gha,mode=max,scope=tango-e2e

      - name: Build sample data
        run: docker compose -f sample/docker-compose.yml run --rm --remove-orphans --entrypoint 'python generate.py ./test -o build/output.json' base

      - name: Start E2E services
        run: docker compose -f .devcontainer/compose.yaml -f .devcontainer/compose.e2e.yaml up --wait --wait-timeout 120 --remove-orphans

      - name: Run E2E tests
        run: docker compose -f .devcontainer/compose.yaml -f .devcontainer/compose.e2e.yaml run --rm --remove-orphans --env CI --entrypoint npm dev run e2e

      - name: Stop E2E services
        if: ${{ always() }}
        run: docker compose -f .devcontainer/compose.yaml -f .devcontainer/compose.e2e.yaml down --volumes --remove-orphans

      - name: Upload Playwright report
        if: ${{ always() }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: playwright-report
          path: |
            playwright-report/
            test-results/
          if-no-files-found: ignore
