name: Integration

on:
  workflow_call:
  workflow_dispatch:

env:
  COMPOSE_PROJECT_NAME: tango-integration
  VITE_DB_HOST: localhost
  VITE_DB_PORT: 8000

jobs:
  firestore:
    name: Firestore
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: jdx/mise-action@v4

      - run: mise run init

      - name: Run Firestore tests
        run: mise run test-firestore

      - name: Stop Firestore emulator
        if: ${{ always() }}
        run: mise run down
