name: Markdown

on:
  pull_request:
    paths:
      - "**/*.md"
  push:
    branches:
      - main
    paths:
      - "**/*.md"

permissions:
  contents: read

jobs:
  linter:
    name: Linter
    uses: ./.github/workflows/linter.yaml
